# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jross5/Desktop/DataPath/MainMemory/MainMemory.srcs/sources_1/ip/MainMemory/MainMemory.xci
# IP: The module: 'MainMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jross5/Desktop/DataPath/MainMemory/MainMemory.srcs/sources_1/ip/MainMemory/MainMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jross5/Desktop/DataPath/MainMemory/MainMemory.srcs/sources_1/ip/MainMemory/MainMemory.xci
# IP: The module: 'MainMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jross5/Desktop/DataPath/MainMemory/MainMemory.srcs/sources_1/ip/MainMemory/MainMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
