# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/jross5/Desktop/DataPath/PC/PC.cache/wt [current_project]
set_property parent.project_path C:/Users/jross5/Desktop/DataPath/PC/PC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC.xci
set_property is_locked true [get_files c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC.xci]

synth_design -top PC -part xc7a100tcsg324-1 -mode out_of_context
rename_ref -prefix_all PC_
write_checkpoint -noxdef PC.dcp
catch { report_utilization -file PC_utilization_synth.rpt -pb PC_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/jross5/Desktop/DataPath/PC/PC.runs/PC_synth_1/PC.dcp c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/jross5/Desktop/DataPath/PC/PC.ip_user_files/ip/PC]} {
  catch { 
    file copy -force c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC_stub.v C:/Users/jross5/Desktop/DataPath/PC/PC.ip_user_files/ip/PC
  }
}

if {[file isdir C:/Users/jross5/Desktop/DataPath/PC/PC.ip_user_files/ip/PC]} {
  catch { 
    file copy -force c:/Users/jross5/Desktop/DataPath/PC/PC.srcs/sources_1/ip/PC/PC_stub.vhdl C:/Users/jross5/Desktop/DataPath/PC/PC.ip_user_files/ip/PC
  }
}
