# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Justin/Desktop/DataPath/adder64/adder64.cache/wt [current_project]
set_property parent.project_path C:/Users/Justin/Desktop/DataPath/adder64/adder64.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/Justin/Desktop/DataPath/adder64/adder64.srcs/sources_1/new/adder64.vhd
synth_design -top adder64 -part xc7a100tcsg324-1
write_checkpoint -noxdef adder64.dcp
catch { report_utilization -file adder64_utilization_synth.rpt -pb adder64_utilization_synth.pb }
