# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hromalik/Documents/fall2015/Research Paper/xapp1026/XAPP1026/KC705_AxiEth_150MHZ_64KB/HW/RAMcontroller/RAMcontroller.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hromalik/Documents/fall2015/Research Paper/xapp1026/XAPP1026/KC705_AxiEth_150MHZ_64KB/HW/RAMcontroller/RAMcontroller.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/hromalik/Documents/fall2015/Research Paper/xapp1026/XAPP1026/KC705_AxiEth_150MHZ_64KB/HW/RAMcontroller/RAMcontroller.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hromalik/Documents/fall2015/Research Paper/xapp1026/XAPP1026/KC705_AxiEth_150MHZ_64KB/HW/RAMcontroller/RAMcontroller.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
