# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jross5/Desktop/Steding_Ross_Lab6/Lab6_1/registers/registers.cache/wt [current_project]
set_property parent.project_path C:/Users/jross5/Desktop/Steding_Ross_Lab6/Lab6_1/registers/registers.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/jross5/Desktop/Steding_Ross_Lab6/Lab6_1/registers/registers.srcs/sources_1/new/registers.vhd
synth_design -top register_file -part xc7a100tcsg324-1
write_checkpoint -noxdef register_file.dcp
catch { report_utilization -file register_file_utilization_synth.rpt -pb register_file_utilization_synth.pb }
