# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Justin/Desktop/Main/Main/Main.cache/wt [current_project]
set_property parent.project_path C:/Users/Justin/Desktop/Main/Main/Main.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/Justin/Desktop/Main/DataPath/PC.coe
add_files C:/Users/Justin/Desktop/Main/a.coe
add_files -quiet C:/Users/Justin/Desktop/Main/Main/Main.runs/PC_synth_1/PC.dcp
set_property used_in_implementation false [get_files C:/Users/Justin/Desktop/Main/Main/Main.runs/PC_synth_1/PC.dcp]
add_files -quiet C:/Users/Justin/Desktop/Main/Main/Main.runs/MainMemory_synth_1/MainMemory.dcp
set_property used_in_implementation false [get_files C:/Users/Justin/Desktop/Main/Main/Main.runs/MainMemory_synth_1/MainMemory.dcp]
add_files -quiet C:/Users/Justin/Desktop/Main/Main/Main.runs/InstructionMemory_synth_1/InstructionMemory.dcp
set_property used_in_implementation false [get_files C:/Users/Justin/Desktop/Main/Main/Main.runs/InstructionMemory_synth_1/InstructionMemory.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/count_eighthms.vhd
  C:/Users/Justin/Desktop/Main/DataPath/ALU/LSR/LSR.srcs/sources_1/new/LSR.vhd
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/hex_to_7_seg.vhd
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/num_disp_SM.vhd
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/one_hot_dec_anode.vhd
  C:/Users/Justin/Desktop/Main/DataPath/ALU/LSL/LSL.srcs/sources_1/new/LSL.vhd
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/bus_mux_8to1.vhd
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/count_8.vhd
  C:/Users/Justin/Desktop/Main/DataPath/adder64/adder64.srcs/sources_1/new/adder64.vhd
  C:/Users/Justin/Desktop/Main/DataPath/ALU/ALU/ALU.srcs/sources_1/new/ALU.vhd
  C:/Users/Justin/Desktop/Main/DataPath/SignExtender/SignExtender.srcs/sources_1/new/SignExtender.vhd
  C:/Users/Justin/Desktop/Main/DataPath/registers/registers.srcs/sources_1/new/registers.vhd
  C:/Users/Justin/Desktop/Main/DataPath/mux2_to_1_5/mux2_to_1_5.srcs/sources_1/new/mux_2_to_1_5.vhd
  C:/Users/Justin/Desktop/Main/DataPath/mux2_to_1_64/mux2_to_1_64.srcs/sources_1/new/muz2_to_1_64.vhd
  C:/Users/Justin/Desktop/Main/DataPath/RAMcontroller/RAMcontroller.srcs/sources_1/new/display_num.vhd
  C:/Users/Justin/Desktop/Main/ControlUnit/ControlUnit/ControlUnit.srcs/sources_1/new/ControlUnit.vhd
  C:/Users/Justin/Desktop/Main/DataPath/DataPath/DataPath.srcs/sources_1/new/DataPath.vhd
  C:/Users/Justin/Desktop/Main/Main/Main.srcs/sources_1/new/Main.vhd
}
read_xdc C:/Users/Justin/Desktop/Main/Main/Main.srcs/constrs_1/imports/Main/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Justin/Desktop/Main/Main/Main.srcs/constrs_1/imports/Main/Nexys4_Master.xdc]

synth_design -top Main -part xc7a100tcsg324-1
write_checkpoint -noxdef Main.dcp
catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
